language: python
python:
 - "2.7"
before_install:
 - pip install flake8
install:
 - pip install --editable .
before_script:
 - flake8 --exclude=./bikeshed/requests/*,./bikeshed/apiclient/*,./bikeshed/widlparser/* ; true
script: bikeshed test
