# See https://packaging.python.org/appveyor/

environment:
  matrix:
  - PYTHON: C:\\Python27
  - PYTHON: C:\\Python27-x64
install:
- cmd: >-
    %PYTHON%\\python -m pip install -U pip wheel setuptools

    %PYTHON%\\python -m pip install -U flake8
build_script:
- cmd: '%PYTHON%\\python.exe -m pip install --editable .'
test_script:
- cmd: >-
    %PYTHON%\\python.exe -m flake8 --exclude=./bikeshed/requests/*,./bikeshed/apiclient/*,./bikeshed/widlparser/* || cmd /c "exit /b 0"

    %PYTHON%\\Scripts\\bikeshed.exe test
